let current=0,answers=Array(QUESTIONS.length).fill(null),seconds=0,timer=null;
const $=id=>document.getElementById(id);
function start(){ $('startScreen').classList.add('hidden');$('testScreen').classList.remove('hidden'); timer=setInterval(()=>{seconds++;$('timer').textContent=fmt(seconds)},1000);render();}
function fmt(s){return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function render(){const x=QUESTIONS[current];$('sectionLabel').textContent=x.section;$('questionCount').textContent=`Question ${current+1} of ${QUESTIONS.length}`;$('topicLabel').textContent=x.topic;$('questionText').textContent=x.q;$('progressBar').style.width=((current+1)/QUESTIONS.length*100)+'%';const c=$('choices');c.innerHTML='';x.a.forEach((v,i)=>{const b=document.createElement('button');b.className='choice'+(answers[current]===i?' selected':'');b.textContent=String.fromCharCode(65+i)+'. '+v;b.onclick=()=>{answers[current]=i;render()};c.appendChild(b)});$('prevBtn').disabled=current===0;$('nextBtn').classList.toggle('hidden',current===QUESTIONS.length-1);$('submitBtn').classList.toggle('hidden',current!==QUESTIONS.length-1);renderJump();}
function renderJump(){const j=$('jump');j.innerHTML='';QUESTIONS.forEach((q,i)=>{const b=document.createElement('button');b.textContent=i+1;if(answers[i]!==null)b.classList.add('done');if(i===current)b.classList.add('current');b.onclick=()=>{current=i;render()};j.appendChild(b)})}
function submit(){const unanswered=answers.filter(x=>x===null).length;if(unanswered){if(!confirm(`You have ${unanswered} unanswered question${unanswered===1?'':'s'}. Submit anyway?`))return;}clearInterval(timer);showResults();}
function scaled(raw){return Math.round(200+(raw/10)*20)}
function showResults(){ $('testScreen').classList.add('hidden');$('resultsScreen').classList.remove('hidden'); const total=answers.reduce((n,a,i)=>n+(a===QUESTIONS[i].correct?1:0),0); const overall=Math.round(200+(total/50)*200); const sections=[...new Set(QUESTIONS.map(q=>q.section))]; let html=`<div class="card"><h2>Diagnostic Complete 🎉</h2><div class="score">${overall}</div><p><strong>Estimated OAT-style Academic Diagnostic Score</strong></p><p>${total}/50 correct (${Math.round(total/50*100)}%). This is an unofficial practice estimate and does not reproduce the ADA's actual scoring conversion.</p><div class="resultGrid">`;sections.forEach(s=>{const qs=QUESTIONS.filter(q=>q.section===s),score=qs.reduce((n,q)=>n+(answers[q.n-1]===q.correct?1:0),0);html+=`<div class="resultBox"><span>${s}</span><strong>${scaled(score)}</strong><small>${score}/${qs.length} correct</small></div>`});html+='</div></div><div class="card"><h2>Review Missed Questions</h2>';let missed=0;QUESTIONS.forEach((q,i)=>{if(answers[i]!==q.correct){missed++;html+=`<div class="missed"><strong>Question ${q.n} — ${q.section}</strong><p>${q.q}</p><p class="incorrect">Your answer: ${answers[i]===null?'Not answered':q.a[answers[i]]}</p><p class="correct">Correct answer: ${q.a[q.correct]}</p><p>${q.exp}</p></div>`}});if(!missed)html+='<p class="correct"><strong>Perfect diagnostic!</strong> No missed questions.</p>';html+=`</div><button class="restart" onclick="location.reload()">Retake Diagnostic</button>`;$('resultsScreen').innerHTML=html;}
$('startBtn').onclick=start;$('prevBtn').onclick=()=>{if(current>0){current--;render()}};$('nextBtn').onclick=()=>{if(current<QUESTIONS.length-1){current++;render()}};$('submitBtn').onclick=submit;
